esphome:
  name: audio-stream-example
  platform: ESP32
  board: esp32-s3-devkitc-1

external_components:
  - source: github://cusnir/esphome-audio-stream@main
    components: [ audio_stream ]

# Enable web server
web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable Home Assistant API
api:

# Enable OTA updates
ota:

# I2S Audio configuration
i2s_audio:
  id: i2s_audio_id
  i2s_lrclk_pin: 11
  i2s_bclk_pin: 12
  i2s_din_pin: 10
  sample_rate: 16000

# Audio stream configuration
audio_stream:
  i2s_audio_id: i2s_audio_id
  websocket_server: "ws://your_server:3000"
  buffer_size: 512
  debug_mode: true
